module.exports = (db) => {
  const funds = [
    {
      name: "Communication Services ETF",
      ticker: "VOX",
      asset_class: "Stock - Sector",
      risk_level: 5,
      expense_ratio: 0.1,
      investment_min: 131.91,
      price: 131.91,
      change_price: -1.16,
    },
    {
      name: "Consumer Discretionary ETF",
      ticker: "VCR",
      asset_class: "Stock - Sector",
      risk_level: 5,
      expense_ratio: 0.1,
      investment_min: 320.08,
      price: 320.08,
      change_price: -5.79,
    },
    {
      name: "Consumer Staples ETF",
      ticker: "VDC",
      asset_class: "Stock - Sector",
      risk_level: 5,
      expense_ratio: 0.1,
      investment_min: 193.19,
      price: 193.19,
      change_price: -0.14,
    },
    {
      name: "Dividend Appreciation ETF",
      ticker: "VIG",
      asset_class: "Stock - Large-Cap Blend",
      risk_level: 4,
      expense_ratio: 0.06,
      investment_min: 164.67,
      price: 164.67,
      change_price: -2.58,
    },
    {
      name: "Emerging Markets Government Bond ETF",
      ticker: "VWOB",
      asset_class: "International",
      risk_level: 3,
      expense_ratio: 0.25,
      investment_min: 76.89,
      price: 76.89,
      change_price: -0.34,
    },
    {
      name: "Energy ETF",
      ticker: "VDE",
      asset_class: "Stock - Sector",
      risk_level: 5,
      expense_ratio: 0.1,
      investment_min: 74.11,
      price: 74.11,
      change_price: -0.97,
    },
    {
      name: "ESG International Stock ETF",
      ticker: "VSGX",
      asset_class: "International",
      risk_level: 5,
      expense_ratio: 0.12,
      investment_min: 59.85,
      price: 59.85,
      change_price: -0.55,
    },
    {
      name: "ESG U.S. Corporate Bond ETF",
      ticker: "VCEB",
      asset_class: "Bond - Inter-term Investment",
      risk_level: 2,
      expense_ratio: 0.12,
      investment_min: 73.51,
      price: 73.51,
      change_price: -0.23,
    },
  ];

  funds.forEach((fund) => db.funds.insert(fund));
};
